[package]
name = "mmv"
version = "0.1.0"
authors = ["Pete Bevin <pete@petebevin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.1.0"
